### ISSUE TITLE
followup TODO items - client certificate authentication [from PR #1]

### ISSUE THREAD

**Issue by brody2consult** [brodybits/cordova-plugin-ios-xhr#2]
followup items from PR #1 now published as version `0.0.1-rc01` __(updated):__

- [ ] update `README.md` with info about client certificate authentication & requirement to install [updated] `cordova-plugin-client-certificate-support`
- [x] ~~publish update to `cordova-plugin-client-certificate-support` with https://github.com/cordova-ccafix/cordova-plugin-client-certificate-support/pull/12~~
- [ ] add explicit plugin dependency - needs `cordova-plugin-client-certificate-support` with https://github.com/cordova-ccafix/cordova-plugin-client-certificate-support/pull/12 in order to build & run properly
- [x] ~~clean up comments~~
- [x] ~~clean up logging~~
- [ ] publish a more stable non-rc version
